import pandas as pd
from openpyxl.utils import get_column_letter
from openpyxl.styles import Alignment, Font, PatternFill

ROWS = [
    ("AMLS", "AML Service",
     "AML 연계 서비스\n\n코나카드 결제 플랫폼과 AML 솔루션을 연계",
     "AML Interface Service\n\nInterface Service Between KonaCard And AML Solution"),
    ("ACS", "Accumulation Calculation System",
     "누적 시스템\n\n거래에 대한 누적 정보를 관리함\n\n누적 정보 기준으로 각 종 이벤트에 제공될 수 있도록 함",
     "Cumulative system\n\nManage cumulative information on transactions\n\nProvided to various events based on accumulated information"),
    ("AGS", "Authorization Gateway Service",
     "인증 게이트웨이 서비스 컴포넌트\n\nJWT Token 을 사용하여 인증된 API 만 특정 서버로 Routing 수행",
     "Authorization Gateway Service\n\nRouting only authenticated API using JWT Token to a specific server"),
    ("APIGW", "API Gateway",
     "앱 요청 게이트웨이 서비스 컴포넌트\n\n사용자 월렛과 서비스 서버간의 세션을 관리하며, 사용자 월렛의 다양한 API 호출을 각 Component 에 라우팅 한다. 또한 보안키보드 관련 작업과 API 버전을 관리한다. 최종 응답단계에서 동일한 포맷으로 에러메시지를 변경후 각국의 언어에 맞게 지역화 시킨다. 현재는 국문/일문/중문/영문 에러메시지를 제공한다.",
     "Route api call from wallet to service layer and core component. Handle secure keyboard related operation. Uniform error response and provide localized error message"),
    ("APS", "Authentication processing server",
     "코나카드의 충전단말기의 거래를 인증하기 위한 보안수단으로 Card Activation 및 충전/충전취소 거래 시 단말기에 설치된 SAM으로 연산된 MAC값을 검증한다.",
     "Verify Mac value computed by SAM, which is connected to charging terminal, when Card Activation, Charging and Charging cancellation. This is a security method to authenticate transaction b/w KonaCard and Charging terminal."),
    ("BAS", "Bconline Authentication Service",
     "BC온라인거래 발생 시 코나카드 별도로 내부검증이 필요하다. 이 때 사용되는 Cryptogram을 생성한다.",
     "Internal verification is required when Bc Online Transaction is occured. BAS generate cryptogram value which is used for this transaction case."),
    ("VVAN", "Virtual-Value Addition Network",
     "가맹점/단말기 검증\n\nvan사 역할 대행\n단말기 개통/정보 수정\n단말기 및 가맹점 검증\n온라인/오프라인 결제거래 검증\n\nISO8583 형식 검증\n거래 검증 및 결제 로직 수행\n코나샵/캐시비",
     "verify merchant/cat or pos terminal\n\nverify status of affiliate and terminal\nopen terminal and correct its information.\nverify online/offline payment transaction\n\nISO8583 full text format\nkona direct payment/cashbee"),
    ("BGS", "Bank Gateway Service",
     "은행 게이트웨이 서비스 컴포넌트\n\n은행 Gateway 컴포넌트 로서, 은행에서 제공하는 API 기반으로 은행 업무 로직을 수행",
     "Bank Gateway Service\n\nAs a bank gateway component, it performs banking logic based on the API provided by the bank."),
    ("BIZB", "business Batch server",
     "행안부 데이터(dis) ↔ 비즈포탈에서 승인할 수 있는 데이터를 변환하여 양쪽에 업데이트 쳐주는 서버\n\n행안부 데이터를 코나카드 정보와 결합하여 비즈포탈에 넘겨주고 반대로 지급 이후에는 지급이력을 행안부 데이터에 업데이트 치는 역할을 하고 있다.\n\n온라인 신청/오프라인 신청 각각 배치를 통해 승인 데이터를 만들고 있음",
     "A component which transform Goverment data into biz portal data so that kona operator can see and confirm the rechargeable data."),
    ("BIZS", "business portal API server",
     "BPP(business portal platform)의 데이터와 코나카드 코어와의 데이터 통신을 위한 API 서버(월렛서버에 떠있음). 주로 BPP만 가지고 있는 정보(정책수당 수혜자 정보)의 검증(수당 대상자가 맞는지)이 필요할 때 사용된다.\n\n카드등록, 카드교체 액션이 일어날 때 수당 지급을 위해 비즈서버에도 저장하려고 호출되며, 매일 배치를 통해 지급일에 도달한 수당을 지급하는 일도 하고있다.",
     "Api server for BPP to communicate with core components. Especially used for checking if he/she is right person to receive money and provide/withdraw point or balance."),
    ("BTS", "Barcode Translator Service",
     "QR코드 정보 생성을 위한 서버 컴포넌트",
     "Server component for generating QR code information"),
    ("CA", "Certificate Authority",
     "인증서발급 및 전자서명을 위한 컴포넌트로, Portal에서 상품 및 가맹점을 등록/승인할 때 사용한다.",
     "Use as a component for certificate issuance and digital signature when registering and approving products and affiliates at portal."),
    ("CAMS", "card application manage system",
     "체크 카드 신청 및 발급을 관리한다.",
     "A component to manage check card issue and status."),
    ("PMS", "pocket money management service",
     "용돈 관리 서비스를 제공한다.",
     "Provide pocket money management service."),
    ("CARDSE", "CardSE",
     "실물카드(CardSE)의 발급과 폐기를 관리하고, 실물카드(CardSE)와 모바일카드(HCE 카드)의 연결 또는 복제 기능을 제공한다.",
     "- Batch Raw data generation controls, Batch Tokenization,\n\nDownload new HCE card with CardSE, Connect anactiveCardsewithan active HCE, Activate/Deactivate CardSE in the system after issuance"),
    ("CDM", "Card Delivery Management(System)",
     "웰컴 카드, 정책수당카드 등 코나카드의 배송을 관리하는 컴포넌트로, App에서 회원가입 완료시 신청한 정보(혹은 EDM, CALL, BIZ 등에서 넘어온 정보)를 코나C공장으로 전달하여 다음날 배치를 통해 배송이 되도록 한다. 배송 후 공장의 완료파일을 읽어 상태 값/카드번호 등을 업데이트 치고 있다.\n\n또한 배송신청데이터를 앱/포탈 등에 보여주기 위한 조회 API를 제공하고 있다. 비용부과카드 구매, 재발급구매카드 신청 시 비용한 금액 등도 관리한다.\n\n(단,코나샵의 카드 배송과 무관)",
     "A component to manage deliveries of KonaCard such as welcome card, Acuon card, SKT card and Pentaport card.\n\nHave Kimpo factory deliver by sending requested batch information which is from other companies after signing up at APP. This is irrelevant to KONA Shop's delivery."),
    ("CLR", "Clearing",
     "코나카드 정산 컴포넌트\n\n코나카드 거래 데이터를 기반으로 계약서에 의거하여 수수료 및 대금을 확정하고 확정된 대금에 대한 지급 데이터 생성, 지급에 대한 근거 자료를 생성한다.\n거래 데이터는 승인단에서 정산에 필요한 원장 데이터를 파일 형태로 전달받고 부가적인 데이터는 관련 컴포넌트에 저장된 정보를 이용한다.\n정산은 서비스 운영에 영향을 미치지 않도록 비교적 거래가 적은 새벽 시간 대에 배치로 수행된다.",
     "Confirm commission and payment amount based on Konacard's transaction data.\n\nCreate payment data for confirmed payment amount and its related evidences."),
    ("CRMS", "Corporation Recharge Management Service",
     "법인 계좌 출금이체후 카드에 충전 컴포넌트\n\n쿠콘 출금이체 수행후, 카드 충전 요청 수행\n실제 서비스는 HOLD 되었으나, 법인 계좌 출금 요청을 수행하고 있음\n(출금이체 API, 충전 API, 출금이체 + 충전 API 가 분리되어 있음",
     "Corporation Recharge Management Service"),
    ("CMS", "Card Management System",
     "카드 원장 관리\n\n카드 발급을 위한 로우 데이터 생성\n모든 카드의 PAN 및 PAR 생성\nPAN : 카드 고유 번호\nPAR : 카드 고유 번호에 대한 닉네임 (거래에 사용)\n모든 카드에 대한 라이프사이클 관리\n카드 기반 정보 관리\n\n소득공제\n기명화",
     "Create and manage card number of mobile card and plastic card(for internal use only), expiry date, life cycle and full text.\n\nSupport income tax deduction as an additional function."),
    ("CRS", "Customer Reward System",
     "리워드 관련 정보 등록/업데이트/삭제 등의 관리와 활성화된 리워드에 따른 실시간 리워드 지급을 위한 조건 검사 기능을 제공한다.\n\n다음 두 가지 종류에 대한 실시간 리워드 지급이 가능하다.\n\nPoint\nCoupon\n다음 세 가지 상황에 실시간 리워드 지급을 할 수 있다\n\n회원가입\n카드등록\n결제 / 충전",
     "Manage reward-related registration, update, deletion.\n\nSupport condition check function to grant real time reward on activated reward."),
    ("CS", "Charge Service",
     "은행계좌 및 신용 카드를 통한 충전 기능 온라인 충전상 충전을 담당한다.\n\n사용자는 계좌주 실명 조회, ARS 인증을 거쳐, 은행 계좌를 앱에 등록할 수 있다. 등록된 계좌를 통해, 코나카드에 충전을 할 수 있다.\n\n외부 PG사와의 연동을 통하여 고객 계좌에서 출금이체가 이루어지도록 한다.\n\n사용자는 월별 자동 충전 또는 기준 하한 자동 충전 설정을 통해, 추가적인 입력 없이, 조건에 따라 자동으로 충전되는 기능을 지원한다.",
     "CS manages charging via bank account or credit card to kona card. Users can register their bank accounts in the app via account name lookup, ARS verification. Users can charge Kona cards through the registered account.\n\nThe withdrawal from the customer's account is made through the interlocking with the external PG company.\n\nThe user can charge automatically according to conditions, without any additional input, either through monthly automatic charging or standard low automatic charging setting."),
    ("CVS", "Certificate Verification Service",
     "외부 인증 모듈로 현재 주민등록증 인증과 운전면허증 인증을 제공한다. 소득공제 및 충전한도 상향시 신분증 인증을 사용한다.\n\n주민등록증 인증 - 정부24\n운전면허증 인증 - 경찰청",
     "The external authentication module provides current resident registration certificate and driver's license certification."),
    ("DCP", "Digital Card Platform",
     "모바일 카드 관리\n\n모바일 카드 토큰 관리\n라이프 사이클 관리\nDELETE : 삭제\nACTIVE : 활성화\nSUSPENDED : 정지\n키 관리\n모바일 거래에 사용되는 암호화 키 관리",
     "Manage digital card life cycle. Manage transaction keys and replenishment"),
    ("DDA/DDV", "Display data service",
     "App을 위한 전시데이터 제공용 API 서비스",
     "API service for providing exhibition data for App"),
    ("DMS", "Donation Management Service",
     "기부 서비스\n\n포인트 or 잔액을 통한 기부 서비스",
     "Donation Service\n\nuser donate point or cash to charity"),
    ("EAS", "External Alliance Service",
     "외부 제휴 서비스를 위한 컴포넌트\n\nKB PLCC\nCU Membership\n상품 서브스 코드 관리",
     "server component for external alliance service\n\nKB PLCC Card\nCU Membership\nService code menagement"),
    ("EDM", "External Data Manager",
     "외부 서비스 제휴사와의 커뮤니케이션을 담당하는 컴포넌트이며 제휴사로부터 서비스에 필요한 정보를 수집하거나 제휴사에게 부가 서비스를 제공한다. 제휴사별 정책에 따라, 제휴사 카드 등록 시, 혜택을 제공하는 기능, 제휴사 충전 기능, 은행 계좌 등록 시, 제휴사 계좌 정보 제공 기능을 지원한다.\n\n제휴사는, 모두, SKT, 통합콜, 아들에날린, 농협은행이 있다.",
     "EDM is a component responsible for communication with external service partners and collects information necessary for the service from affiliates or provides additional services to affiliates.\n\nAccording to the affiliate policy, it supports the function of providing benefits when registering an affiliate card, the function of charging an affiliate, the function of providing information of an affiliate account when registering a bank account.\n\nAffiliates are MODU, SKT, Unified Call, Nonghyup bank."),
    ("EGS", "External Gateway System",
     "Portal과 고객센터 등 외부 컴포넌트가 코어 API와 소통하는 Gateway 역할을 한다.\n\nGateway 리스트\n\netn, itn, map, ias, apigw, cdm, cardse, cms, kps, kcs, knotify, , userporal, gs, kcps, crs, cs, rs, vvan, edm, tsp, bizs, kmp",
     "A Gateway for external components such as Portal and Customer Center to communicate cord API."),
    ("EIM", "Electronic ID Management System",
     "기업에서 패용되는 사원증의 발급 및 출입권한 통제, 코나카드시스템과 연동하여 선불카드와 결합하여 사용할 수 있다.\n\nBPP와 통합되어 사용안함 (2018.10.31)",
     "Issue employee identification"),
    ("ELASTIC", "ELASTIC Search",
     "연계된 지자체의 충전, 결제, 유저정보의 빅데이터 처리 및 지자체 전송을 진행 하는 역할을 한다.",
     "It plays a role in charging, payment, big data processing of user information, and transmission to local governments."),
    ("EMS", "Echo Mileage Service",
     "인천 서구 환경 마일리지 서비스를 위한 컴포넌트",
     "It is a server for providing environmental mileage service in Seo-gu, Incheon, and serves to provide mileage by linking walking and cycling partners."),
    ("EPMS", "External Portal Data Management Service",
     "외부 지자체 포탈의 데이터를 연동하는 컴포넌트로 해당 데이터는 App 전시데이터로 활용된다.",
     "It is a component that links data on external local government portals, and the data is used as app exhibition data."),
    ("EWSM", "External Web Service Manager",
     "외부 웹 서비스와의 연동을 담당하는 컴포넌트이다.\n\n현재, MG신용정보(주) 와 서비스 연동을 통해, ARS 서비스를 제공하고 있다. ARS 서비스를 통해, 수당 카드 등록, 준준회원 가입, 카드 분실 및 분실 해제, 소득 공제 신청, 카드 잔액 및 포인트 조회 기능을 제공한다.",
     "EWSM is a component responsible for communication with external web service partners.\n\nAt this moment, EWSM provide ARS service with MG Credit Info affiliate.\n\nThrough out ARS, it provides allowance request, deduction, card lost & lost release, semi-user register."),
    ("FDMS", "FDS Management System",
     "마스터카드 해외결제의 이상금융거래탐지(FDS)를 검증하기 위해 매입사인 KB와의 연동을 담당하는 컴포넌트이다.",
     "It is a component in charge of linking with KB, the buyer, to verify the abnormal financial transaction detection (FDS) of MasterCard's overseas payment."),
    ("FDS", "Fraud Detection System",
     "이상금융거래탐지(FDS)는 3가지의 주요업무를 수행한다.\n\n이상탐지(Detection) : 기초 데이터를 사전 정의된 정책으로 분석하여 이상거래를 도출한다.\n정책정의(Policy) : 이상거래로 도출하기 위한 정책을 정의하고 이상탐지 시 정의된 사항으로 이상금융거래로 도출되도록 한다.\n이상조치(Response) : 이상금융거래로 도출된 정보를 바탕으로 해당 플레이어를 대상으로 금융거래의 제제를 가한다.",
     "The component FDS will do three major jobs:\n\ndetect the fraud: Based on the policy defined previously, FDS will detect fraud transaction.\ndefine the policy: Define the policy for fraud transaction.\ndeal with the frauds: Based on the accumulated information of the user and the policy, FDS will manage his/her fraud history and stop/resume his/her transaction."),
    ("FPS", "Fee Policy System",
     "과금 시스템\n\n서비스 이용 따른 과금 관리 서비스",
     "Fee Payment System\n\nBilling management service according to service use"),
    ("FTM", "File transfer management",
     "파일전송관리 시스템",
     ""),
    ("GS", "Gift Service",
     "카드 선물, 쿠폰 선물 및 송금을 관장하는 컴포넌트로, 선물 및 송금 전송에 따른 상태를 관리하고 전송자와 수신자를 이어주는 역할을 한다.\n\n선물 서비스에는, \"사용자간 선물 서비스\", \"어드민 선물 서비스\"이 있으며, 송금 서비스에는 \"사용자간 송금\", \"카드로 직접 송금\"으로 나뉜다.",
     "GS manages card gift, coupon gift, and remittance.\n\nIt manages the status of the gift and remittance transfer and connects the sender and receiver.\n\nCard/Coupon gift service includes \"user gift service\" and \"administrator gift service\", and remittance service is divided into \"user transfer\" and \"card direct transfer\"."),
    ("IAS", "Issuer authorization system",
     "카드의 최종 원장을 관리하며 라이프사이클 및 카드 잔액과 서비스에 필요한 상태 등을 관리한다.\n\n거래발생시 PP를 통해 ISO8583 데이터를 가공하여 승인처리를 진행 및 충전, 지불, 환불 등 거래내역 등을 관리하며 추후 정산에 필요한 데이터를 생성하는 역할을 한다.\n\n카드 원장 및 거래 데이터는 월렛 및 콜센터, 운영UI등에 표현된다.",
     "Manage final register, life cycle, card balance and state for service.\n\nFulfill approval by processing ISO8583 data via PP when transaction occurs.\n\nManage transaction history such as charge, payment and refund to prepare necessary data to calculate at the later date.\n\nCard register and transaction data are reflected in wallet, call center and operation UI."),
    ("ICMS", "Integrated Cash Management System",
     "CMS TCP 통신 컴포넌트\n\n각 외부 제휴사들과 CMS 전문방식으로 파일 송수신 연동을 관리한다. 파일을 송신하는 클라이언트와 파일을 수신하는 서버로 구성되어있다.",
     "It manages file transmission/reception interlocking with each external partner in a CMS-specialized method. It consists of a client sending a file and a server receiving the file."),
    ("ITA(TMS)", "Issuer Token Adapter",
     "크립토그램 검증\n\n거래 요청 수락\n카드 브랜드 및 거래 모드 결정\n위 결정에 따라 크립토그램 검증\n카드 데이터를 통한 비정상 거래 관리\n\nATC 값의 범위 정책을 통해서 거래요청을 검증\n검증 결과가 부적격이면 디지털 카드의 정보를 삭제요청\n토큰 해제\n\nTSP와 통신하여 토큰 해제",
     "Cryptogram Validation\nAccepts transaction request\nDetermines Card Brand and Transaction Mode\nValidates Cryptogram according to Card Brand and Transaction Mode\nFraud Management\n\nChecks validity of data in transaction request and ATC values in the range of accepted values\nRequests to suspend or wipe Digitized Card depending on the outcome of the validation\nDe-Tokenization\n\nDe-tokenizes Token using interfaces with TSP"),
    ("KAS", "Kona Address System",
     "주소 검색 시스템\n\n가맹점 배치 전문 수신 후 테이블 import 시 가맹점의 위경도를 채번하여 넣는다.\n주소 검색을 통해 위경도, 도로명 → 지번 , 지번 → 도로명을 검색할 수 있다.",
     "Search Address System\n\nThe merchant's latitude and longitude are found in the merchant's data import.\nSearch Address And Get Infomation (Road To Jibun, Jibun to Road, zipCode)"),
    ("KCMW", "Kona Consultant Mobile Web",
     "코나카드 모집인을 통해서 회원가입을 한 회원 수 및 일정 금액 이상을 결제한 회원 정보를 모바일 환경을 통해 월별 실적 정보로 제공함으로써 코나카드 모집인들이 자신의 실적을 확인 할 수 있는 정보를 제공하는 컴포넌트이다.",
     "Provide recruiter's monthly record."),
    ("KCPS", "Kona Coupon System",
     "KonaCard 쿠폰 관리 시스템으로, 제휴 인프라에서 사용하는 외부쿠폰과 내부 인프라에서 사용하는 내부쿠폰을 관리한다.\n\nCRS 또는 Admin(Portal), 혹은 쿠폰샵에서 요청하는 쿠폰을 발행 또는 발행 취소 등을 관리 한다.\n\n쿠폰 설정 정보는 KOD가 관리하며 KCPS는 필요 시 KOD를 통해 쿠폰 설정 및 정책에 대한 정보를 취득한다.",
     "It is a KonaCard coupon management system that manages external coupons provided by partner companies and internal coupons used in internal infrastructure.\n\nManage coupon issuance or cancellation requested by CRS, Admin(Portal), or coupon shop.\n\nInformation on setting coupons is managed by KOD, and KCPS obtains information on coupon settings and policies through KOD, if necessary."),
    ("KCS", "Kona Consultant Service",
     "코나카드 고객 유치를 위한 회원 가입을 유도하는 모집인 관련 컴포넌트로 모집인 관리 및 모집인 실적을 제공한다.\n모집인은 다양한 방법으로 코나카드 회원을 모집하며 고객이 가입 시 입력한 추천인 코드를 근거로하여 고객 모집 실적을 판단한다.\n모집인의 실적에 따라서 모집 수수료 내역과 근거 자료를 생성하고 수수료 지급을 할 수 있도록 한다.",
     "A component to provide Core API related to recruiter."),
    ("KFDS", "Kona Fraud Detection System",
     "A-safe를 대신하여 신규로 추가되는 이상금융거래탐지(FDS) 룰을 관리하며 이상거래를 탐지하여 정보를 제공하는 컴포넌트이다.",
     "This is a component that manages the newly added Abnormal Financial Transaction Detection (FDS) rules on behalf of A-safe and detects abnormal transactions and provides information."),
    ("KMC", "Konacard Multi-CRM",
     "고객으로부터 오는 각종 서비스 관련 문의에 대해 신속히 대응하기 위한 고객센터 웹 서버이다. 고객, 가맹점, 비회원배송 등에 대해 조회가 가능하다.",
     "A Customer Center web server to quickly respond to customer's inquiries for various service.\n\nAvailable to check customer, affiliate and nonmember delivery."),
    ("KMS", "Key Management System",
     "HSM 등의 암호화 처리 장비를 이용하여 Key를 안전하게 관리하고 사용하기 위한 편의 기능들을 제공한다.",
     "Communicator between KonaCard component and HSM. Perform encryption/decryption using HSM."),
    ("KNOTIFY", "Knotify",
     "코나카드 서비스의 장애, 통보, 거래 내역 등 알림을 담당한다\n\nNotification Type\n\nSMS\nPush\nE-Mail\nNotification 서비스를 제공하며 API요청으로 전달받은 알림내역을 각 타입에 맞게 전송한다",
     "It is responsible for notification of Kona card service\n\nNotification Type\n\nSMS\nPush\nE-Mail\nNotification service is provided and the notification received by the API request is transmitted according to each type"),
    ("Knotify-DMZ", "Knotify DMZ",
     "푸시 서비스 공급자 컴포넌트간의 라우팅하는 처리로, 컴포넌트의 주요 역할은 knotify가 보낸 푸시를 전달하는 것이다.\n\n푸시 서비스 공급자\n\nFCM (Firebase Cloud Messaging)\nAPN (Apple Push Notification Service)",
     "Push Service Providers Routing between components, the main function of the component is to convey pushes sent by knotify.\n\nPush service provider\n\nFirebase Cloud Messaging (FCM)\nApple Push Notification Service (APN)"),
    ("KOD_ETN", "Kona Operation Desk -External",
     "선불 결제 시스템 운영에 관한 모든 정보(시스템 정책 및 시스템 운영 정보, 파트너 및 상품의 정보)들을 설정하고 관리 할 수 있도록 운영 포탈(플랫폼, 파트너, 비즈등)에 제공한다. 운영 포탈들에 내부 컴포넌트들의 정보들을 조회 및 조합하여 제공하는 역할을 담당한다.",
     "Save system policy along with its operational information, partner and product's information.\n\nWork as a gateway for Portal and internal component to communicate."),
    ("KOD_ITN", "Kona Operation Desk -Internal",
     "선불 결제 시스템 운영에 관한 모든 정보들을 제공한다. Core 컴포넌트 & Wallet App의 요청에 따라 상품 정보, 가맹점 및 기타 Player들에 대한 정보, 시스템 설정 정보, 각종 정책, 할인 정보(즉시할인, 포인트 적립, 단골 할인등), 쿠폰 정보, 결제 우선 순위 및 결제/충전/환불 사용자 수수료 계산 기능, 정산관련 설정 정보등을 제공한다.",
     "This component provides information about products, merchants and other players, system configuration information, various policies, discounts and user fee calculation function by the request of other core components in the system."),
    ("KPF", "Kona Private Funding",
     "계 서비스\n\n한국의 전통 계를 모바일 앱을 통해 제공하는 서비스",
     "Kona Private Funding\n\ntraditional funding of korea\ncreate private group for funding\nprivate group has round which is count of members\neach round pick recipient\nexcept for recipient, member pay funding amount"),
    ("KPS", "Kona Point System",
     "포인트(캐시백)을 관리한다. 정책에 기반한 포인트 적립, 사용, 지급, 차감, 포인트 내역 조회를 제공한다.\n\n포인트는 유저 계정별 포인트(유저포인트), 카드 및 정책별 포인트가 존재하며 각 포인트들의 원장 및 한도관련 처리를 담당한다.\n\n혜택 적립, 포인트 사용, 포인트 자동사용, 포인트 자동 복합 사용, 인센티브 적립, 고객센터 유저 포인트 지급/차감, 수당 지급/회수, 포인트 이용내역, 복지포인트 지급, 환불시 포인트 차감 등을 제공한다.\n\n포인트 소멸- 소멸일자와 이미 사용된 포인트를 계산하여 소멸 대상 포인트를 소멸시킨다.",
     "Manage points (cashback). Provide policy-based point accumulation, usage, payment, deduction, and point tracking.\n\nPoints exist for each user account point (user point), card, and policy, and are responsible for processing related to the ledger and limit of each point.\n\nProvide benefits, points, automatic points, automatic points, incentives, customer center user point payment / deduction, payment / collection of benefits, points of use, payment of welfare points, and deduction of points for refunds.\n\nExtinguish Point - Destroy the expired point by calculating the expiration date and the points already used."),
    ("KSTS", "Kona Stamp System",
     "스탬프 시스템\n\n스탬프 정책 관리\n결제이력에 따른 스탬프 적립/취소\n적립 이력에 따라 보상/보상취소",
     "stamp system\n\nStamp policy management\nStamp accumulation/cancellation according to payment history\nCompensation/compensation cancellation according to accumulation history"),
    ("KDS", "Kona Delivery Service",
     "외부 배달 대행 서비스\n\n배달 대행사 관리\n외부 배달 대행사 접수 연동",
     "Delivery Order Routing Service\n\nManage delivery agency\norder Delivery Service from merchant to customer"),
    ("LOP", "Local Order Platform",
     "배달 서비스\n\n배달 가맹점 관리\n배달 가맹점 매뉴 및 정책 관리\n배달 결제 기능 제공",
     "Delivery service for specific product (ex, food)\n\nManage PLACE (delivery merchant)\nManage Menu and Policy\nServe payment functionality"),
    ("LOP_EXT", "Local Order Platform - Externel",
     "배달 서비스\n\n외부 연동 (재사용 용기)",
     ""),
    ("LOP_DTS", "Local Order Platform - Data Transfer Service",
     "배달 서비스\n\n데이터 관리",
     ""),
    ("MAP", "Mobile Application Platform",
     "회원\n\n회원 가입, 일시중지, 회원 탈퇴 등 회원 서비스 이용 상태를 관리\n비정상 서비스 이용상태를 블랙리스트로 관리\n회원의 Wallet 인증을 Token, password 관리\n회원 가입 시 Device정보를 관리\n회원별 등급 관리(준준회원, 준회원, 정회원)\n약관\n\nASP별 약관 별 관리\n약관에 대한 회원 동의 여부 관리\n프로모션\n\n프로모션 서비스를 위한 회원의 프로모션 코드 관리\n추천인\n\n회원의 추천코드 및 추천 받은 회원의 정보를 관리",
     "Member Management\n\nmember life cycle management(join, suspend, withdrawal )\nnot normal member life cycle(black list)\ntoken, password form certification user for wallet\ndevice of member management\ngrade of member management\nTems\n\ntems management by asp management\naggreement tems by member management\nPromotion\n\nmanage a member's promotional code for promotional services\nRecommender\n\nManagement of member's recommendation letter and recommendation member information"),
    ("MIS", "Mobility Integration Service",
     "모빌리티 연동 서비스\n\n코나모빌리티 & 제휴사 데이터 연동 지원",
     ""),
    ("OASG", "Open API Service Gateway",
     "Gateway for OpenApi",
     "Gateway for OpenApi"),
    ("OASR", "Open API Service Route & Data ReMapping Service",
     "Open API 서비스 컴포넌트\n\n웰컴 저축은행\n애큐온 저축은행\n레몬트리\n코리엠소프트",
     "Server component for Open API\n\nWellcome bank\nAcuon bank\nLemontree\nKORIEMSOFT"),
    ("PCS", "Prepaid Card Service",
     "Wallet App향 Service Layer로 IAS, DCP, PCS, CS, CMS, CDM, KOD_ITN 등 여러 코어 컴포넌트들이 제공하는 정보를 조합하여 선불 카드의 유효기간, 혜택, 정책, 웰컴 카드 등의 카드 기준 정보와 관련된 조회 서비스를 제공하며, 배송관리, 재발급 신청, 다운로드, 삭제, 정지 등 카드의 라이프사이클과 관련된 기본 기능을 관리하는 서비스를 제공한다.",
     "Service layer component. Perform prepaid card related operation (HCE card download, suspend/resume/delete card, card list etc) using core component."),
    ("PCSI", "Prepaid Card Service Inquiry",
     "** 월렛에서 필요한 정보를 수집하여 제공하는 서비스 컴포넌트\n\nIAS, DCP, PCS, CS, CMS, RMS등 여러 코어 컴포넌트들이 제공하는 정보를 조합하여 아래의 정보를 제공한다.\n\n사용자에게 발급 된 카드 목록 제공.\nIAS, DCP, PCS, CardSE, CMS, CS, KPS, KOD_ITN으로부터 정보를 취합하여, 카드번호, 잔액, 서비스명, 닉네임, 기명화 여부, 사용가능한 서비스, 카드 포인트 잔액 등등 정보를 제공한다.\n계정 요약 정보\nIAS, CS, RS, GS, KPS, CMS, KCPS 등으로부터 정보를 취합하여, 카드 개수, 쿠폰 개수, 연결된 계좌 정보, 등 정보를 제공한다.\n사용자가 받은 누적 혜택 정보\n카드 실적 정보\n사용자 환불 진행 정보\n카드 거래내역 정보\n카드 포인트 사용내역 정보\n상점에서 사용가능한 카드 목록",
     "Manage information about purchasing card's PAN, expiry date, balance, benefits and policy by combining information provided by various Core components such as IAS, DCP, PCS, CS, CMS, RMS.\n\nProvide card's transaction history and refund records."),
    ("PP", "Payment Processor",
     "코나카드에서 발생하는 충전/환불/잔액 이동/지불 등 카드와 관련 된 모든 거래의 흐름을 제어한다.\nVAN으로 부터 올라오는 ISO8583 메시지의 Gateway로, 전문의 기본적인 형식을 검증하고 TMS/CMS/IAS 컴포넌트 등에 전달하는 역할을 담당한다.\nTMS를 통해서 크립토그램 및 DCVV 등의 카드 데이터 검증 및 토큰 해제를 수행한다.\n토큰 해제 된 PAN을 IAS에 보내서 거래를 처리한다.\n오프라인 충전/환불 및 온/오프라인 지불의 결과에 대한 사용자 푸쉬 알림 기능을 제공한다.",
     "Controls the flow of all card-related transactions such as recharge/refund/balance transfer/payment that occur on the KONA Card.\nAs a gateway for ISO8583 messages coming from VAN, it is responsible for verifying the basic format of messages and delivering them to TMS/CMS/IAS components.\nThrough TMS, card data verification such as cryptogram and DCVV and token release are performed.\nSend the token-released PAN to IAS to process the transaction.\nOffline recharge/refund and on/offline payment results are provided with user push notifications."),
    ("PRM", "Personal information access record management system",
     "개인정보 접근기록 관리 시스템\n\n플랫폼/고객센터/비즈포탈 에서 관리자가 사용자에 대한 정보를 조회 할 경우 누가 언제 어떤 화면에서 누구를 조회했는지 이력을 남기는 컴포넌트",
     "This is privacy logging component which is called whenever some operator view/search someone's data. it stores who saw who's data at when and where."),
    ("QRS", "Query Running Service",
     "쿼리 실행 서비스, 복잡한 쿼리식을 요하는 서비스 제공 시 빠르게 서비스를 제공할 수 있도록 고안된 컴포넌트\n\n현재까지 사용처\n\n타겟 푸시 서비스\nAPI 리스트\n\n/query POST PUT\n쿼리 서비스 제공을 위한 정책 저장 / 수정\n/query/{queryId} GET\n쿼리 서비스 정책 조회\n/query/{queryId}/run POST\n쿼리 서비스 실행",
     ""),
    ("RPG", "Remote Payment Gateway",
     "코나플랫폼의 온라인PG 역할로, 모바일과 웹사이트의 온라인 결제 기능을 제공한다. 따라서 외부 가맹점에서의 온라인 결제를 관리한다.\n\n외부 가맹점들과 암호화하여 통신한다. RPG는 비대칭키 암호화 방식과 대칭키 암호화 방식을 모두 지원하고 있다. 비밀키를 위해 RPG-KM과 통신한다. RPG는 가맹점의 주문 정보를 저장하고 VVAN과 통신하여 거래를 진행한다.",
     "Online Transaction data preparation and validation, cancel online transactions. So RPG manage online payment from external merchant.\nMerchant communicates with RPG. Communication between merchant and RPG is encrypted. RPG supports both asymmetric and symmetric key cryptographic . It communicate with RPG-KM for secret keys. RPG store merchant order information and communicate with VVAN to make the transaction,"),
    ("RPG-KM", "RPG key management",
     "외부 가맹점과 RPG의 요청에 의해 온라인 거래에 필요한 key를 생성하고 그 주기를 관리한다.",
     "Rpg Key Management (rpgkm) produce, store and manage key life cycle those are required from merchant and rpg component."),
    ("RS", "Refund Service",
     "환불 처리기능을 제공한다.\n\n카드 잔액 계좌 환불, 콜센터 환불, 잔액모으기(코나머니로 잔액이동),잔액 전환(개인이 소유한 카드간 잔액 이동) 기능 제공,\n\n환불 가능 여부 조회, 환불 가능 금액 조회,\n\n환불계좌 성명 인증/환불 계좌 등록/변경/삭제 기능을 제공한다.",
     "Provide refund function such as balance account refund, call center refund, collecting balance, checking refund amount, refund account authentication, registration, change, deletion."),
    ("SAS", "Statistics Analysis System",
     "통계 컴포넌트\n\n코나카드의 거래 추이를 한 눈에 쉽게 알아 볼 수 있도록 거래 데이터를 가공하여 도표 및 그래프로 시각화하여 제공한다.\n고객의 인입 경로, 성별, 연령, 주 사용 시간 등의 정보를 이용하여 다양한 프로모션을 기획하며\n코나카드 마케팅 및 추후 운영 방향을 결정하기 위한 자료로 활용되기도 한다.",
     "Visualize accumulated and daily transaction amount depending on transaction data into statistical data and graph.\n\nThese are the source for Konacard marketing and future operational decisions."),
    ("TCS", "Transaction Compare System",
     "VAN과의 대사 파일을 송신 및 수신한다.\n각 VAN 사 별로의 별도 전문 양식을 기반으로 파일 파싱후 집계 및 해당 집계에 대한 파일을 검증한다.\n또한 VAN사에 대사 파일을 전송하는 기능또한 제공하고 있다.\nVAN사와의 거래 대사를 통하여 정산 대상 거래에 대한 유효성 검증을 진행하여 데이터의 신뢰도를 높인다.\n또한 거래 유효성 검증을 통하여 승인 단의 거래까지 한 번 더 확인하는 작업이 이루어진다.",
     "Send and receive 대사 파일 from/to VAN.\n\nVerify corresponding 대사파일."),
    ("TSP", "Token Service Provider",
     "카드 번호 토큰화\n\n새 토큰 발급\n토큰 해제\n재 토큰화\n대량 토큰화\n토큰 관리\nBIN 관리\n\nPAN BIN 생성 및 관리\n토큰 BIN 관리\nPAN BIN과 토큰 BIN의 매핑 생성",
     "Tokenization\n\nIssue New Token\nDetokenization\nRetokenization\nBulk Tokenization\nRe-Tokenization\nToken Management\nBIN Management\n\nPan Bin Generation and Management\nToken Bin Management\nCreate Pan Bin-Token Bin Mapping"),
    ("GDIS", "Gyeonggi-do Disaster Service",
     "경기도 재난지원금 컴포넌트",
     ""),
    ("MAS", "Mobility Application Service",
     "택시 컴포넌트",
     ""),
    ("MAS-S", "MAS Service",
     "모빌리티 실시간 관제\n\n실시간 택시 위치 Tracking, 실시간 택시 Call 호출 현황 관제",
     ""),
    ("MAS-B", "MAS Batch",
     "모빌리티 통계\n\n모빌리티 포탈로 부터 택시 통계 데이터 조회 API 제공\n\nIAS로 부터 택시 서비스 실시간 거래 데이터 수신 후 적재\n\nCLR로 부터 정산 데이터 수신 후 적재",
     ""),
    ("MAS-J", "MAS Job",
     "모빌리티 배치\n\n모빌리티 통계/정산 데이터에 대한 배치 작업 수행",
     ""),
    ("ETH", "Event To Hadoop",
     "택시 이벤트 투 하둡 저장 컴포넌트",
     ""),
    ("RDS", "Realtime Dispatcher Service",
     "택시 실시간 위치 트레킹 및 요청 전송 컴포넌트",
     ""),
    ("ESP", "Elastic Search Platform",
     "엘라스틱서치 - 택시정보 관리 컴포넌트",
     ""),
    ("BUSAN", "Busan Core Service",
     "부산 동백전 정보 이관 연계 컴포넌트\n\n동백전 회원 정보 이관\n회원 가입 완료시, 회원 정보 이관 및 신규 wallet 회원 ID 매핑 처리\n동백전 잔액 정보 이관\n카드 발급 완료시, 잔액 정보 이관 처리\n동백전 이용 내역 정보 이관",
     ""),
    ("ETMS", "Entry Ticket Management System",
     "응모권 발급\n\n이벤트 발생에 따른 응모권 발급\n응모정책 별 중복없는 응모권번호 채번\n1회 요청에 중복없는 사용자에 대해 어드민응모권 발급",
     "the issuance of an entry ticket\n\nIssue entry tiekcts for users who meet the event conditions\nGenerate entry ticket numbers without duplicates for each entry policy\nIssue Admin entry tickets for users who do not have duplicates in one request"),
    ("MYDS", "",
     "마이데이터 정보제공자 컴포넌트",
     ""),
    ("MYDG", "",
     "마이데이터 정보제공 서비스를 위한 Gateway 컴포넌트",
     ""),
    ("PIS", "",
     "선불카드조회 서비스 컴포넌트 - 신규\n\n** 월렛에서 필요한 정보를 수집하여 제공하는 서비스 컴포넌트\n\nIAS, DCP, PCS, CS, CMS, RMS등 여러 코어 컴포넌트들이 제공하는 정보를 조합하여 아래의 정보를 제공한다.\n\n사용자에게 발급 된 카드 목록 제공.\nIAS, DCP, PCS, CardSE, CMS, CS, KPS, KOD_ITN으로부터 정보를 취합하여, 카드번호, 잔액, 서비스명, 닉네임, 기명화 여부, 사용가능한 서비스, 카드 포인트 잔액 등등 정보를 제공한다.\n계정 요약 정보\nIAS, CS, RS, GS, KPS, CMS, KCPS 등으로부터 정보를 취합하여, 카드 개수, 쿠폰 개수, 연결된 계좌 정보, 등 정보를 제공한다.\n사용자가 받은 누적 혜택 정보\n카드 실적 정보\n사용자 환불 진행 정보\n카드 거래내역 정보\n카드 포인트 사용내역 정보\n상점에서 사용가능한 카드 목록",
     "Manage information about purchasing card's PAN, expiry date, balance, benefits and policy by combining information provided by various Core components such as IAS, DCP, PCS, CS, CMS, RMS.\n\nProvide card's transaction history and refund records."),
    ("TSS", "Transfer(Take-over) Support Service",
     "이관 지원 서비스\n\n회원 정보 이관\n잔액 정보 이관\n체크 카드 연동 정보 이관\n거래 내역 정보 이관",
     "Support to take over from other company service\n\nTransfer User Information\nTransfer Balance Information\nTransfer Debit Card Information\nTransfer Transactions Information"),
    ("UIS", "User Identification Service",
     "코나카드 사용자의 신분증 진위 확인을 검증한다.",
     "Verifies the authenticity of the KONA CARD user's ID."),
    ("OASL", "Open API Service Layer",
     "No HCE 기반 오픈 API 서비스 레이어\n\n코나 Health\nJADU\nPINO",
     "Server component for Open API (No HCE)\n\nKona Health"),
    ("LSS", "Luckyloco Support Service",
     "코나카드 플랫폼과 럭키로코 서비스 연계 지원",
     "Support Servicee Between Konacard and Luckyloco"),
    ("YBAT", "KonaYs Batch Service",
     "KonaYs Batch Service",
     "KonaYs Batch Service"),
    ("YSTORE", "KonaYs Store Service",
     "KonaYs Store Service\nKonaYs 프로젝트용 데이터 수집 서비스",
     "KonaYs Store Service"),
    ("RFS", "Request For Subsidy",
     "보조금 24 (내게 맞는 정책수당 찾기 서비스)",
     "Request For Subsidy"),
    ("SPS", "Secure Phonenumber Service",
     "안심번호 제공 서비스",
     "Secure PhoneNumber Service"),
    ("TTS", "Taxi Transaction System",
     "택시 거래 시스템\n\n앱미터기 전문 연동 후 VAN사를 통해 신용카드 거래 중계\n중계된 거래 수집시스템\n정산파일 제공",
     "Taxi Transaction System\n\nIntermediate credit card transaction through VAN company after professional linkage of Appmeter terminal\nRelayed transaction collection system\nSettlement file provided"),
    ("KBC_B", "KONA business card Batch",
     "복지카드 배치서비스",
     "Welfare card batch service"),
    ("LOP_RDS", "LOP Realtime Dispatcher Service",
     "LOP 실시간 폴링 서비스",
     "LOP Realtime Dispatcher Service\n\nlop realtime polling service"),
    ("CSG", "Call Service Gateway",
     "지역전화콜 연동 서비스\n\n지역전화콜 시스템과 코나택시(MAS) 사이에서 호출 서비스 중계",
     "Call Service Gateway\n\nTransfer call service between local call system and Kona taxi system(MAS)"),
    ("CPG", "Credit Payment Gateway",
     "신용카드 결제 게이트웨이\n\nEZPS에서 관리하는 카드정보를 통해 카드 간편결제 거래 중계\n정산데이터 제공",
     "credit card payment gateway\n\nPayment transactions are delivered to credit card companies using card information managed by EZPS.\nSettlement data provided"),
    ("EZPS", "Easy Payment Service",
     "신용카드 간편 결제 관리 서비스",
     "Credit card easy payment management service"),
    ("ETM", "Event To Mongo",
     "택시 이벤트 투 MongoDB 저장 컴포넌트",
     ""),
    ("IMCS", "IMCS",
     "교통정산 컴포넌트 (Integrated Mobility Clearing and Settlement)\n\n신용카드사의 EDI 가맹점으로 교통 PG 역할을 수행함\n거래데이터를 수집하여, VAN or 신용카드사에 대표가맹점으써, 매입요청을 하고 매입 완료 되면 정산 대금을 받아서, 택시 사업자에게 정산함\nOnline 결제 : 신용카드사 직연동\nOffline 결제 : VAN 사 연동",
     "Integrated Mobility Clearing and Settlement\nIt serves as a transportation PG as an EDI affiliate of a credit card company\n Collect transaction data, make a purchase request to VAN or credit card company, receive the settlement price when the purchase is completed, and settle it with the taxi operator\nOnline payment: Direct connection with credit card companies\nOffline Payment: Interworking with VAN Company"),
    ("DAPM", "Display Advertisment Platform Messagebroker",
     "광고 플랫폼 메세징 컴포넌트\n\n광고 서비스는 모든 요청을 메세지로 관리하기에 광고 서비스 가장 앞단에서 모든 요청을 받는 서버\n받은 요청을 정규화를 통해 메세지 큐로 전달하는 역할",
     "Advertising platform messaging components\n\nThe ad service manages all requests by message, so the server that receives all requests at the front end of the ad service\nResponsible for forwarding received requests to message queues through normalization"),
    ("DAPC", "Display Advertisment Platform Core",
     "광고 플랫폼 코어 컴포넌트\n\nDAPM 로 부터 발생된 메세지를 받아, 광고 서비스에 사용할 수 있도록 가공 및 저장, 집계 등을 담당",
     "Advertising Platform Core Components\n\nResponsible for processing, storing, and aggregating messages from DAPM for use in advertising services"),
    ("DAPA", "Display Advertisment Platform API",
     "광고 플랫폼 API 컴포넌트\n\n광고 기능 중 API 로 제공되어야할 기능들을 담당",
     "Advertising platform API components\n\nResponsible for the functions that should be provided as API among advertising functions"),
    ("MONIS", "Monitoring Interface Service",
     "관제 / 택시 시스템 간의 연동 컴포넌트\n\n관제 시스템과 택시 호출 시스템의 데이터 연동하기 위한 인터페이스 컴포넌트",
     "Interface component between taxi system and FMS system"),
    ("CBSS", "Customer Benefit segmentation statics",
     "고객 혜택 집계 관리 컴포넌트\n\nIAS, KPS의 거래 데이터를 수집하여 혜택 유형별 집계 데이터를 제공",
     "Customer Benefit Aggregation Management Component\n\nCollects transaction data from IAS and KPS to provide aggregate data by benefit type"),
    ("CAS", "Card Authentification Service",
     "카드 인증 서비스\n\n간편결제 카드인증, 구인증, 해외결제 인증, 직가맹 카드인증 서비스를 제공",
     "Card Authentification Service\n\nProvides simple payment card authentication, old authentication, and direct affiliate store card authentication services."),
    ("PLD", "Personal Identifiable Information Leak Detection",
     "개인 정보 유출 탐지 컴포넌트\n\nISMS-P 인증 용 개인 정보 유출 탐지 기능을 담당",
     "Personal information leak detection components\n\nProvides personal information leak detection service for ISMS-P certification"),
    ("MDPS", "Mobility Data Purge Service",
     "모빌리티 데이터 삭제 서비스\n\nISMS-P 관련하여 데이터 삭제 및 익명화 기능 담당",
     "Mobility Data Purge Service\n\nResponsible for Data Deletion and Anonymization Functions in ISMS-P policy"),
    ("ORS", "Overseas Remittance Service",
     "해외 송금 서비스",
     "Manage overseas remittance service"),
    ("VCC", "Visible Chatbot Core",
     "보이는 챗봇 코어 서비스\n\n사용자로부터 전달받는 메세지를 특정 인덱스에 따라서 사용자를 가이드하고 메세지를 AI 코어 서비스로 전달하는 서비스\n\n기획자로부터 정의받은 인덱스를 관리하는 서비스",
     "Visible Chatbot Core\n\nResponsible for receive user message from VCF components and lead to follow certain indexes and send message to AI core service\n\nResponse for management certain indexes defined by project manager"),
    ("AICC", "AI Contact Center",
     "AI 고객센터\n\n고객 문의 의도 파악\n시스템 정책과 개인화 데이터를 기반으로 AI 알고리즘을 활용하여 고객 서비스 운영 간소화",
     "AI Contact Center\n\nUnderstanding the intent of customer inquiries\nThe system simplifies customer service operations by utilizing AI algorithms based on system policies and personalized data"),
    ("VAS", "Voice Assistant Service",
     "음성 비서 서비스\n\n음성을 텍스트로(STT), 텍스트를 음성으로(TTS) 변환",
     "Voice Assistant Service\n\nSpeech to Text(STT), Text to Speech(TTS)"),
    ("AMM", "AppMeter Manager",
     "앱미터 매니저\n\n앱미터 단말기 개통, 해지, 설정 업데이트를 하는 서비스",
     "AppMeter Manager\n\nService for opening, canceling, and updating settings of AppMeter terminals"),
    ("MSMA", "Mobility Supply-chain Management Api Service",
     "모빌리티 자산 관리 시스템\n\n모빌리티 자산에 대한 관리를 하는 서비스",
     "Mobility Supply-chain Management Api Service"),
    ("MSMW", "Mobility Supply-chain Management Web",
     "모빌리티 자산 관리 시스템 포탈\n\n모빌리티 자산에 대한 관리하는 포탈",
     "Mobility Supply-chain Management Web"),
    ("MOSP", "Mobility OTA Service Portal",
     "모빌리티 OTA 서비스 포탈\n\n앱미터 OTA 관리 포탈",
     "Mobility OTA Service Portal"),
    ("VCF", "Visible Chatbot Front",
     "보이는 챗봇\n\n사용자로부터 전달받는 메세지를 특정 인덱스에 따라서 사용자를 가이드하고 메세지를 AI 코어 서비스로 전달하는 서비스",
     "a visible chatbot\n\nA service that guides users according to specific indexes and delivers messages to AI core services"),
    ("FXS", "Foreign eXchange Service",
     "외환 관리 서비스\n\n외화 계좌 및 매입/매도 내역 관리\n실시간 환율 조회 서비스 제공\n보유 외화 환율 평단가 관리\n외화 매입/매도 정산",
     "Foreign Exchange Service\n\nManaging foreign currency accounts and purchase/sale details\nProviding real-time exchange rate inquiry service\nManaging the unit price of foreign currency exchange rate held\nSettlement of foreign currency purchases/sale"),
    ("LBMS", "Location-Base Merchant Service",
     "위치 기반 가맹점 서비스\n\n위치 기반 가맹점 정보 조회를 위해 Elasticsech에 가맹점 정보를 관리 및 조회",
     "Location-Base Merchant Service\n\nManagement and inquiry of merchant information to Elasticsech for location-based merchant information inquiry"),
    ("MASI", "Mobility Application Service Interface",
     "모빌리티 택시 데이터 조회 서비스\n\n포탈에서 데이터 Read 전용(masm, masp, ...)",
     "Mobility taxi data inquiry service\n\nRead only data from portal(masm, masp, ...)"),
    ("COPS", "Co-Payment Service",
     "모아서 결제 서비스\n\n결제참여 요청 및 승인/거절\n모으기 / 모으기 취소\n모아서 결제",
     "Collection payment service\n\nPayment participation request and approval/rejection\nCollect / Cancel Collect\nCollect and pay"),
    ("KS-BATCH", "KS data batch server",
     "고객센터 모니터링을 위한 배치\n\nKS의 CTI 데이터 중 일부를 조회 해 KONAI DB에 적재한다.\nKS의 데이터를 실시간으로 보기 위해 API를 제공한다.",
     "Batch Server for Customer Center Monitoring\nSome of KS's CTI data are inquired and loaded into the KONAI DB.\nWe provide an API to view KS's data in real time."),
    ("DBMT", "Database Monitoring",
     "데이터베이스 모니터링 컴포넌트 (API 서버)\n\nx7, x8, x9 의 db cpu 부하 상태에 대한 API를 제공한다.",
     "Database monitoring component (API server)\n\nProvides API for DB CPU load status of x7, x8, x9."),
    ("VAM", "Virtual Account Management",
     "가상 계좌 매핑 및 관리 서비스",
     "Virtual Account Management service"),
    ("RDMT", "Rundeck Monitoring",
     "런덱 모니터링 컴포넌트 (API 서버)\n\n런덱의 구동 상태, 스케쥴 진행 상태 등에 대한 API를 제공한다",
     "Rundeck monitoring component (API server)"),
    ("AICV", "AI Contract Validation",
     "가맹점 계약 검증 컴포넌트 (API 서버)\n\n가맹점 계약 검수 API를 제공한다.",
     "Merchant Contract Validation component (API server)"),
    ("SCC", "Spring Cloud Config",
     "OpenAPI 관련 컴퍼넌트 설정 정보 통합 관리 컴퍼넌트\n\nTGS의 설정 정보 변경 시 서비스 재시작 없이 API를 통해서 실시간 반영하도록 설정 정보를 제공한다.\n컴퍼넌트 필요 시 통합 관리 설정 정보 추가 가능",
     "Component of Management Configuration\n\nWhen TGS configuration information is changed, the configuration information is provided to be reflected in real time through API without restarting the service.\nIntegrated management setting information can be added when required for components"),
    ("SDTS", "Secure Document Transfer System",
     "솔리데오 PINO 전자문서지갑 서비스 제공",
     "Secure Document Transfer System"),
    ("CLR_KT", "Clearing Kotlin",
     "코나카드 정산 컴포넌트는 거래 데이터를 기반으로 수수료와 대금을 계산하고, 지급 데이터를 생성합니다. Spring Boot 3.2.3, JDK 21, Kotlin으로 업그레이드된 CLR_KT로 새롭게 제공됩니다. 정산은 서비스에 영향을 주지 않도록 새벽 시간에 자동으로 처리됩니다.",
     "The Kona Card Clearing kotlin component calculates fees and payments based on transaction data and generates payment data. Previously built with Spring Boot 1.x, JDK 8, and Java, it has now been upgraded to CLR_KT, using Spring Boot 3.2.3, JDK 21, and Kotlin. Clearing kotlin processes are automatically handled during early morning hours to avoid service disruption."),
    ("PRS", "Personalized Recommendation System",
     "개인 맞춤형 추천 시스템\n\n사용자의 활동 이력을 기반으로 자주 사용하는 서비스를 알려주고, 사용자를 성별/연령대/지역 등으로 구분해 그룹화하여 그룹별 선호하는 서비스를 분석하여 사용자 맞춤 서비스를 추천해준다.",
     "Personalized Recommendation System\n\nBased on the user's activity history, it informs frequently used services, groups users by gender/age group/region, and analyzes preferred services for each group to recommend customized services."),
    ("OPBO", "Open Partner Back-Office",
     "개방형 플랫폼 제휴 파트너 API 사용량 대시보드/통계\n\nKonaplate를 사용하는 제휴사들의 API 사용량, 통계 및 기타 서비스를 제공한다.",
     "Open Partner Back-Office\n\nProvides API usage, statistics, and other services for affiliates using Konaplate."),
    ("KTC", "Kona Traffic Controller",
     "트레이서 대기열 솔루션을 내재화한 프로젝트\n\n앱/웹 진입 의 특정 Zone 진입 시 N분 당 M명의 사용자만 접속을 허용하며, 대기중인 사용자에게 현재 대기열 순번을 제공한다.",
     "Project Internalizing Tracer Queue Solutions\n\nWhen entering a specific zone of app/web entry, only M users are allowed to access per N minutes, and the current queue sequence is provided to the waiting users."),
    ("KTCA", "Kona Traffic Controller API Server",
     "트레이서 대기열 솔루션을 내재화한 프로젝트의 API 서버\n\n특정 Zone 에 대한 N분당 M명의 사용자만 접속 허용하는 정책을 반영하며, 실시간 Zone 및 대기열 현황을 시각화하기 위한 데이터를 제공한다.",
     "API servers for projects that internalize tracer queue solutions\n\nIt reflects a policy that allows access to only M users per N minutes for a specific zone, and provides data for visualizing real-time zone and queue status."),
    ("STT", "SpeechToText",
     "음성파일을 텍스트로 변환기능 제공",
     "Provides the ability to convert voice files to text"),
    ("AFS", "Annual Fee Service",
     "연회비 서비스.\n\n카드 혜택에 따른 정기 결제를 담당한다.\n\n결제는 카드 출금 실패 시 계좌 출금 순으로 진행한다.",
     "Annual fee service.\n\nIt's responsible for the recurring payments based on card benefits.\n\nPayments are processed first by card debit and then by bank account debit if the card payment fails."),
    ("CIMS", "Card Inventory Management Service",
     "카드 재고 관리 서비\n\nE2MAX 와 연동하여 카드 재고를 관리한다.",
     "Card Inventory Management Service\n\nManage card inventory in conjunction with E2MAX."),
    ("IIS", "Instant Issue Service",
     "즉시 발급 서비스",
     "Instant Issue Service"),
    ("ACC", "Agent Chatbot Core",
     "지역화폐 챗봇 에이전트 - 코어 서버.\n\nAI(LLM) + 지역화폐 관련 문서 + 여러 Wallet 서버들의 정책 / 개인화 정보들을 조합하여 응답한다.\n\n민감정보는 마스킹 처리된다.",
     "The Core Server generates responses by synthesizing AI (LLM), local currency-related documentation, and the specific policies and personalized information from various Wallet servers.\n\nData Synthesis: Integrates LLM capabilities with domain-specific knowledge bases and real-time wallet data.\n\nData Security: All sensitive information is processed using masking to ensure privacy."),
    ("ACW", "Agent Chatbot Web",
     "지역화폐 챗봇 에이전트 - 웹 서버.\n\nACC와 SSE 통신을 하며 사용자에게 화면을 실시간 렌더링한다.",
     "The Web Server handles the real-time interface, communicating with the ACC via SSE to render screens for the user.\n\nCommunication: Utilizes SSE (Server-Sent Events) for persistent, real-time data flow.\n\nUI Rendering: Executes real-time screen rendering to provide a seamless user experience."),
    ("MLS", "Mileage service",
     "마일리지 서비스\n\n마일리지 적립, 사용, 취소, 만료 기능을 제공 한다.",
     "Mileage Service\n\nProvides functions for accumulating, using, canceling, and expiring mileage."),
]

PORTAL_ROWS = [
    ("AMP", "Asp Management Portal",
     "직불승인 고객사 운영자에게 제공되는 포탈 서비스 입니다. (웰컴저축은행 고객사용)",
     "This is a portal service provided to the operator of direct payment approval.",
     "웰컴저축은행 관리포탈", "https://amp.konacard.co.kr"),
    ("ATC", "Administrator To Card",
     "Bulk로 카드에 포인트 및 잔액을 충전하기 위한 시스템입니다. (코나 재무팀)",
     "This is a component for Charge Deposit or Card-Cash to Cards.(only for administrator)",
     "재경포탈", "https://atc.konacard.co.kr"),
    ("BIZA", "Business Portal A",
     "오프라인 긴급재난지원금 신청 관리사이트\n(재난지원금 신청자, 공무원)",
     "",
     "배치", ""),
    ("BIZCC", "Business Portal Covidoff",
     "현장지급 시스템 지급 데이터를 관리하는 API 서버.\n\n지급을 위한 지자체별 정책수당정보를 관리하며 지급명단 등록기능을 지원한다.",
     "API server that manages on-site payment system. It manages the cash policy information for each local gov. and supports registering the payment list.",
     "삭제", ""),
    ("BIZD", "Business Portal D",
     "지역화폐 이용 가맹점 등록을 위한 사이트이다. (지사상)\n(지자체별 가맹점주, 공무원)",
     "This is a site for registering affiliate stores using local currency.",
     "지역사랑상품권 가맹점 신청 사이트", "https://with.konacard.co.kr"),
    ("BIZCF", "Business Portal Front",
     "현장지급 시스템 지급관리를 위한 운영 포탈.\n\n지급등록/지급관리/통계 등을 UI로 제공한다.\n\n(지자체 공무원, 정책수당 지급, 지급 통계 제공)",
     "Operation portal for on-site payment system. Payment registration/payment management/statistics are provided through the UI.",
     "현장지급시스템", "https://cc.konacard.co.kr/gateway"),
    ("BIZU", "Business Portal CU",
     "CU 과일 바우처 신청을 위한 사이트.\n\n(지자체 공무원, 정책수당 신청, 신청 통계 제공)",
     "This is the site for applying for CU Fruit Voucher.",
     "바우처 신청 서비스", "https://voucher.konacard.co.kr"),
    ("URC", "User Right Commission",
     "지역화폐 가맹점 신고를 위한 사이트.",
     "Site for reporting affiliated merchant.",
     "삭제", ""),
    ("DDA", "Display Data Api",
     "앱 전시 데이터 API 서비스\n(데이터 표시 무관)",
     "",
     "API", ""),
    ("DDV", "Display Data webView",
     "앱 전시 데이터 웹뷰 서비스\n(데이터 표시 무관)",
     "",
     "웹뷰", ""),
    ("DISF", "Business Portal Disaster Front",
     "긴급재난 지원금 2차 신청을 위한 사이트 (강릉, 인제..)",
     "Site for the 2nd application for emergency disaster support fund.",
     "삭제", ""),
    ("DISC", "Business Portal Disaster Core",
     "긴급재난 지원금 2차 신청을 위한 API 서버(강릉, 인제..)",
     "API server for the 2nd application of emergency disaster support fund.",
     "삭제", ""),
    ("DISG", "Business Portal Disaster Core",
     "제2차 경기도 재난지원금 신청을 위한 사이트\n\n없어졌는지 확인 필요???\n\n==> 네. 해당 컴포넌트 종료되었습니다.",
     "Site for applying for disaster support fund in Gyeonggi-do",
     "삭제", ""),
    ("DISG3", "Business Portal Disaster Core",
     "제2차 경기도 재난지원금 신청을 위한 사이트\n\n없어졌는지 확인 필요???\n\n==> 네. 해당 컴포넌트 종료되었습니다.",
     "",
     "삭제", ""),
    ("DISG3_PC", "Business Portal Disaster Core",
     "제3차 포천시 재난지원금 신청을 위한 사이트",
     "Site for the 3rd Pocheon City Disaster Assistance Application",
     "삭제", ""),
    ("DISG3_AS", "Business Portal Disaster Core",
     "제3차 안성시 재난지원금 신청을 위한 사이트",
     "Site for the 3rd Anseong-si Disaster Assistance Application",
     "삭제", ""),
    ("DISG4_AS", "Business Portal Disaster Core",
     "제4차 안산시 재난지원금 신청을 위한 사이트",
     "Ansan-si, Gyeonggi-do 4th Disaster Subsidy Application Site",
     "삭제", ""),
    ("DISG4_GR", "Business Portal Disaster Core",
     "구리시 재난기본소득 신청을 위한 사이트",
     "Guri City Disaster Basic Income Application Site",
     "삭제", ""),
    ("DISG3_IC", "Business Portal Disaster Core",
     "제3차 이천시 재난지원금 신청을 위한 사이트",
     "Site for the 3rd Icheon City Disaster Assistance Application",
     "삭제", ""),
    ("DISGF", "Business Portal Disaster Core",
     "제2차 경기도 외국인 재난지원금 신청을 위한 사이트",
     "Site for applying for disaster support fund for foreigners in Gyeonggi",
     "삭제", ""),
    ("DISG_PJ", "Business Portal Disaster Core",
     "경기도 파주 재난기본소득 지급처리",
     "Site for applying for disaster support fund in Gyeonggi-do Paju",
     "삭제", ""),
    ("DISG_GJ", "Business Portal Disaster Core",
     "경기도 광주 재난기본소득 지급처리",
     "Site for applying for disaster support fund in Gyeonggi-do Gwangju",
     "삭제", ""),
    ("DISG_AS", "Business Portal Disaster Core",
     "경기도 안성 재난기본소득 지급처리",
     "Site for applying for disaster support fund in Gyeonggi-do Ansung",
     "삭제", ""),
    ("DISN_ON", "Business Portal Disaster Core",
     "코로나 상생 국민지원금 온라인 신청 사이트",
     "Corona coexistence national support fund online site",
     "삭제", ""),
    ("DISN_OFF", "Business Portal Disaster Core",
     "코로나 상생 국민지원금 오프라인 신청 사이트",
     "Corona coexistence national support fund offline site",
     "삭제", ""),
    ("DRG", "Business Portal Disaster Core",
     "인천시 일상회복지원금 온라인 신청 사이트",
     "Incheon City Daily Recovery Fund Online Application Site",
     "삭제", ""),
    ("DRG_OFF", "Business Portal Disaster Core",
     "인천시 일상회복지원금 오프라인 신청 사이트",
     "Incheon City Daily Recovery Fund Offline Application Site",
     "삭제", ""),
    ("BPP(bizp)", "Business Portal Platform",
     "코나카드 B2B, B2C, B2G 서비스를 위한 포탈서비스 플랫폼.\n\n코나카드를 활용한 다양한 수요부의 서비스 요구사항을 빠르게 대응하고자 개발된 플랫폼이다.\n\n여기서의 서비스란 특정 대상이 이용하고자하는 기능의 묶음 단위로, 서비스의 단위로 포탈서비스로 제공한다.\n\n주로 제공하는 기능은, 파트너, 상품관리, 포인트/잔액 지급 및 회수, 거래내역, 통계화면 제공 등이다.\n\n(RCS 포함, 지역화폐 관리 포탈)",
     "The Potal Service Platform for B2B, B2C, and B2G service of KONA CARD.\n\nThis Potal is developed to deal with various service requirement from relevant departments that utilizes KONA CARD .\n\nHere service implies to a bundle of functions that a target group aims to utilize. And this is provided as a portal service.",
     "지역화폐 관리 포탈",
     "https://ccp.konacard.co.kr (법인/복지카드서비스 관리포탈)\nhttps://gg.konacard.co.kr (경기지역화폐 관리포탈)\nhttps://partner.konacard.co.kr (제휴사 고객관리서비스)\nhttps://ic.konacard.co.kr (인천광역시 복지카드 관리포탈)\nhttps://rcs.konacard.co.kr (오프라인 판매지원포탈)\nhttps://report.konacard.co.kr (REPORT SERVICE)\nhttps://dj.konacard.co.kr (대덕e로움 관리포탈)\nhttps://bs.konacard.co.kr (부산지역화폐 관리포탈)\nhttps://icpay.konacard.co.kr (인천지역화폐 관리포탈)\nhttps://ys.konacard.co.kr (양산지역화폐 관리포탈)\nhttps://ygpay.konacard.co.kr (영광지역화폐 관리포탈)\nhttps://cjpay.konacard.co.kr (청주지역화폐 관리포탈)\nhttps://ywpay.konacard.co.kr (영월지역화폐 관리포탈)\nhttps://gnpay.konacard.co.kr (강릉지역화폐 관리포탈)\nhttps://uscpay.konacard.co.kr (의성지역화폐 관리포탈)\nhttps://espay.konacard.co.kr (음성지역화폐 관리포탈)\nhttps://capay.konacard.co.kr (천안지역화폐관리포탈)\nhttps://gbgspay.konacard.co.kr (경산지역화폐관리포탈)\nhttps://tbpay.konacard.co.kr (태백지역화폐관리포탈)\nhttps://gcpay.konacard.co.kr (김천지역화폐관리포탈)\nhttps://ocpay.konacard.co.kr (옥천지역화폐관리포탈)\nhttps://gjpay.konacard.co.kr (경주지역화폐관리포탈)\nhttps://ijpay.konacard.co.kr (인제지역화폐관리포탈)\nhttps://ujpay.konacard.co.kr (울진지역화폐관리포탈)\nhttps://bsngpay.konacard.co.kr (부산남구지역화폐관리포탈)\nhttps://gspay.konacard.co.kr (고성지역화폐관리포탈)\nhttps://dhpay.konacard.co.kr (동해지역화폐관리포탈)\nhttps://hspay.konacard.co.kr (횡성지역화폐관리포탈)\nhttps://mrpay.konacard.co.kr (밀양지역화폐관리포탈)\nhttps://gppay.konacard.co.kr (김포지역화폐관리포탈)\nhttps://ulsan.konacard.co.kr (울산지역화폐관리포탈)"),
    ("KFM", "Kona File Manager",
     "코나카드 의 대용량 엑셀 파일 을 다운로드 하기 위한 컴포넌트입니다.\n\n(파일 제작용으로 데이터와 무관)",
     "This is a component to download Kona Card's large Excel file.",
     "파일다운로드기능만", ""),
    ("KMC", "Kona Multi Callcenter",
     "코나카드의 콜 센터 업무를 지원하기 위한 시스템입니다.\n\n코나카드의 고객 대응 기능을 제공합니다.\n\n(고객센터 화면)",
     "It is a system to support call center business of Kona card.\n\nKona Card's customer support function.",
     "고객센터용", ""),
    ("KMP", "Kona Merchant Portal",
     "가맹점 주들이 자신이 가진 가맹점에서 일어난 거래내역 및 통계정보를 확인할 수 있습니다.\n\n승인된 가맹점 주들은 자신의 가맹점들에 대해서 거래 취소, 가맹점 소개 정보 입력,수정등의 관리를 할 수 있습니다.\n\n(지자체별 가맹점 포탈)\n→ MPT로 변경됨\n(Phase 67.0 배포 이후 컴포넌트 종료) 홍종표팀장확인(24.03.18) → 68.0 이후로 연기(3/15)",
     "Merchant owners can check transaction history and statistical information that occurred at their merchant.\nApproved merchants can manage their franchisees by canceling transactions, merchant intro information, and modifying them.",
     "삭제", ""),
    ("LAP", "Laos Audit Portal",
     "라오토토 회계정산 포탈",
     "This is a component for Laototo audit.",
     "삭제", ""),
    ("MING", "Mobileweb Into Native Group",
     "앱에서 QR을 표시하기 위한 웹 컴포넌트\n\n(데이터와 무관)",
     "Web component for displaying QR in the app",
     "QR표시용", ""),
    ("MPT", "Merchant Portal Two",
     "기존 KMP의 두번째 버전입니다.\n\n가맹점 주들이 자신이 가진 가맹점에서 일어난 거래내역 및 통계정보를 확인할 수 있습니다.\n\n승인된 가맹점 주들은 자신의 가맹점들에 대해서 거래 취소, 가맹점 소개 정보 입력,수정등의 관리를 할 수 있습니다.\n\n(지자체별 가맹점 포탈)",
     "Merchant owners can check transaction history and statistical information that occurred at their merchant.\nApproved merchants can manage their franchisees by canceling transactions, merchant intro information, and modifying them.",
     "가맹점주 전용 포탈",
     "https://gg.merchant-portal.co.kr\nhttps://incheon.merchant-portal.co.kr"),
    ("OASP", "Open Api Service Portal",
     "오픈api 설정을 위한 포탈\n(어디서 사용? 데이터와 무관? OAuTH ??)",
     "portal for kona open api service",
     "오픈API관리", ""),
    ("Partner Portal", "Partner Portal",
     "코나카드서비스를 이용하는 파트너(가맹점)가 접속하여 각종 거래/정산 내역을 조회하고 판매하고 싶은 각종 상품을 등록하고 관리한다.\n(외부 제공 없음, 내부에서 사용)",
     "A partner (merchant) who uses the Kona card service inquiry various transaction / settlement details, and registers and manages various products that they want to sell.",
     "파트너사 전용 포탈", "https://partner.konaplatform.com/"),
    ("platform portal", "Platform Portal",
     "Partner포탈에서 요청한 상품 및 가맹점에 대한 검증 및 승인, 각종 정산 정보, 및 코나 플랫폼을 운영하기 위한 기본 정보(ASP별 약관 등록, 단말기관리, 메시지 템플릿 등)를 관리한다.\n\n(내부에서 사용, 통계/집계/정산 등 포함)",
     "The Partner portal manages the verification and approval of the requested products and merchants, various settlement information, and basic information (ASP registration, terminal management, message template, etc.) for operating the Kona platform.",
     "내부 관리자용 포탈", "https://platform.konaplatform.com:10580"),
    ("PMP", "Payable Merchant Portal",
     "경기지역화폐 사용가능 매장을 찾기 위한 서비스입니다.\n\n(검색 서비스, 통계 정보 없음)",
     "This service is used to find local currency-denominated stores.",
     "검색서비스", ""),
    ("RFSP", "Recommendation For Subsidy Portal",
     "보조금 24 포탈\n\n→ 만들어 놓고 내부/지자체 모두 사용하지 않고 있음.\n\n==> 해당 컴포넌트 종료되었습니다.",
     "The 'Subsidy 24' portal is a portal to support public officials.",
     "보조금24 지급 관리 포탈", "https://subsidy.konacard.co.kr/"),
    ("System Portal", "System Portal",
     "코나카드발급을 위한 전문생성 및 코나카드시스템을 운영하기 위한 마스터 데이터를 관리한다.\n(시스템에서 필요하는 디폴트 정보 등)\n(Processing실 사용, 통계/집계 데이터 무관)",
     "This portal manages communication creation for issuing Kona cards and register master data for operating the Kona card system. (Such as the default information required by the system)",
     "운영설정", ""),
    ("TBOSB", "Total BackOffice Service Batch",
     "차세대포탈 서비스 제공을 위한 배치 서비스입니다.\n\n(UI 없음. 백엔드)",
     "It is a batch service to provide next-generation portal services.",
     "배치", ""),
    ("TBOS", "Total BackOffice Service",
     "차세대포탈 서비스.\n\n(내부에서 사용, 통계/집계/정산 등 포함)",
     "next-generation portal(Platform Portal)",
     "내부 관리자용 포탈", "https://tbos.konacard.co.kr:10004"),
    ("TBOST", "Total BackOffice Service ThirdParty",
     "차세대포탈 서비스 제공을 위한 Thridpary DB 데이터 제공을 위한 서비스.\n\n(UI 없음. 백엔드, 3rd Party 연결 목적)",
     "A service for providing Thridpary DB data.",
     "3rd Party연결기능", ""),
    ("TBOS_A", "Total BackOffice Service ACCOUNT",
     "차세대포탈을 위한 통합계정 신청 서비스\n(토탈백오피스 통합계정관리서비스(회원가입+권한신청+개인정보수정))",
     "Integrated account application service",
     "계정관리", ""),
    ("TBOS_AB", "Total BackOffice Service ACCOUNT-API",
     "차세대포탈을 위한 통합계정 인증 서비스\n(토탈백오피스 통합계정관리 API 서비스)",
     "Integrated account authentication service",
     "API연동", ""),
    ("TBOS_AM", "Total BackOffice Service ACCOUNT Management",
     "차세대포탈을 위한 통합계정 관리 서비스\n(토탈백오피스 통합계정관리 API 서비스, 관리자용)",
     "Integrated account Management service",
     "API연동", ""),
    ("TDIS", "Business Portal Total Disaster",
     "신규 긴급재난 지원금 신청을 위한 사이트\n(지자체 공무원, 내부, 신청자 전부 사용)",
     "Site for the new emergency disaster support fund.",
     "재난지원금 신청 사이트", "https://tdis.konacard.co.kr"),
    ("User Portal", "User Portal",
     "사용자에게 코나카드서비스에 대한 각종 상품 및 가맹점 등에 대한 정보를 조회할 수 있도록 하기 위한 코나카드서비스 홈페이지와 같은 기능을 제공한다.\n\nkonacard.co.kr\n\n(지역화폐 홈페이지)",
     "This portal provides a function such as a Kona card service homepage for allowing a user to inquire information on various products and merchant points related to the Kona card service.",
     "코나카드 홈페이지", "https://www.konacard.co.kr/"),
    ("usersite", "user site",
     "앱이 없는 사람이, 코나카드를 사용하고자 할 때 회원가입/카드배송/이용내역확인 등을 할 수 있게 하는 ui\n(사용자용, 거래 내역 실시간 조회 등)",
     "when user with no phone(app) wants to use Konacard system, this site will provide functions such as user registration, card delivery, transaction history.",
     "유저사이트",
     "konacard.usersite.co.kr\ngyeonggi.usersite.co.kr\nincheoneum.usersite.co.kr\nbusan.usersite.co.kr\nmiryang.usersite.co.kr"),
    ("ESIGN", "ESIGN",
     "코나카드 서비스 신청을 온라인으로 진행 할 수 있는 전자계약 서비스 입니다.\n(가맹점주 사용)",
     "This is an electronic contract service that allows you to apply for Kona Card service on online.",
     "직가맹 전자계약 신청 사이트", "https://esign.konacard.co.kr"),
    ("MASP", "Mobility PARTNER Portal",
     "코나 모빌리티 비지니스 파트너 포탈\n(모빌리티용 포탈)",
     "",
     "모빌리티", ""),
    ("MASM", "Mobility Management Portal",
     "코나 모빌리티 관리자 포탈",
     "",
     "모빌리티", ""),
    ("MASV", "Mobility View Api",
     "코나 모빌리티 전시 Api 서비스",
     "",
     "모빌리티", ""),
    ("MAS_VOP", "Mobility Voucher Portal",
     "코나모빌리티 바우처관리포탈(김포)",
     "Mobility Voucher management Portal(MamaCall)",
     "모빌리티", ""),
    ("MAS_VOV", "Mobility Voucher View",
     "코나모빌리티 바우처전시(김포)",
     "Mobility Voucher management View(MamaCall)",
     "모빌리티", ""),
    ("MAS_VOS", "Mobility Voucher Service API",
     "코나모빌리티 바우처서비스",
     "Mobility Voucher Service API(MamaCall)",
     "모빌리티", ""),
    ("KBC_P", "KONA business card Portal",
     "복지카드 포탈서비스\n\n(복지카드 제휴사 포탈)",
     "Welfare card portal service",
     "코나비즈포탈", "https://konabizcard.com"),
    ("KBC_B", "KONA business card Batch",
     "복지카드 배치서비스\n\n(복지카드 제휴사 배치용)",
     "Welfare card batch service",
     "배치", ""),
    ("DISG_GC", "Business Portal Disaster Core",
     "과천시 재난기본소득\n\n→ 아직 있는지? 확인 필요\n\n==> 해당 컴포넌트 종료되었습니다.",
     "Site for applying for disaster support fund in Gyeonggi-do Gwacheon",
     "삭제", ""),
    ("DISG_PT", "Business Portal Disaster Core",
     "평택시 생활안정지원금\n→ 아직 있는지? 확인 필요\n\n==> 해당 컴포넌트 종료되었습니다.",
     "Pyeongtaek City Livelihood Security Subsidy Administrative Processing System",
     "삭제", ""),
    ("IEPS", "Integrated execution processing system",
     "정책지원금 통합집행처리 시스템\n\n(지자체/공무원 사용)",
     "Integrated execution processing system for policy support funds",
     "정책지원금 통합집행처리 시스템", "https://ieps.konacard.co.kr/ (내부망/vpn)"),
    ("IBFP", "Inbound foreigner Portal",
     "외국인 인바운드 포탈 컴포넌트\n\n(외국인 포탈, 여행사용/내부 관리자용)",
     "Foreign inbound portal component",
     "코나트래블 시스템\n(외국인 관광객 어드민 포탈)", "https://travel.konacard.co.kr/"),
    ("VCF", "Visible Chatbot Front",
     "crm ai 챗봇 서비스 웹UI\n\n(고객센터용 챗봇 UI)",
     "This service is an ai-chatbot service that will replace the CRM operating personnel.\n\nThis chatbot was created to replace the customer center operator, and VCF provides AI chatbot UI.",
     "챗봇", ""),
    ("IBFA", "Inbound foreiner Api",
     "외국인 인바운드 API\n(외국인 포탈, 여행사용/내부 기능 백엔드)",
     "Foreign inbound API component",
     "API", ""),
    ("KPG", "Kona Payment Gateway",
     "NHN KCP를 통해 신용카드로 선불 카드 충전 서비스",
     "Prepaid card recharge service via credit card through NHN KCP.",
     "코나 PG 시스템", ""),
    ("ECA", "Easy Card Apply",
     "웹페이지를 통해 코나카드를 신청할 수 있는 사이트",
     "A website where you can apply for a KonaCard online.",
     "", ""),
    ("OPBO", "Openpartner Back-office",
     "OpenAPI를 사용하는 제휴사를 위한 백오피스 시스템",
     "Back office system for affiliates using OpenAPI",
     "", "opbo.konacard.co.kr"),
    ("OGD", "Onsite Grant Disbursement",
     "현장지급 시스템",
     "Operation portal for on-site payment system. Payment registration/payment management/statistics are provided through the UI.",
     "", ""),
]

# Merge: original components keep their KR/EN; portal info attached when Name matches.
# Portal-only entries are appended with the new portal description.
portal_by_name = {r[0]: r for r in PORTAL_ROWS}
seen = set()
combined = []
for name, full, kr, en in ROWS:
    if name in portal_by_name:
        _, _, _, _, p_name, p_url = portal_by_name[name]
        combined.append((name, full, kr, en, p_name, p_url))
        seen.add(name)
    else:
        combined.append((name, full, kr, en, "", ""))
for name, full, kr, en, p_name, p_url in PORTAL_ROWS:
    if name not in seen:
        combined.append((name, full, kr, en, p_name, p_url))

# Sort ascending (A, B, C ...) — case-insensitive ASCII order
combined.sort(key=lambda r: r[0].upper())

OUT = r"D:\da\components.xlsx"
COLUMNS = ["Name", "Full Name", "한글 설명", "English Description", "Portal Name", "Portal URL"]
df = pd.DataFrame(combined, columns=COLUMNS)

with pd.ExcelWriter(OUT, engine="openpyxl") as writer:
    df.to_excel(writer, index=False, sheet_name="Components")
    ws = writer.sheets["Components"]

    widths = {"A": 16, "B": 38, "C": 60, "D": 60, "E": 28, "F": 50}
    for col, w in widths.items():
        ws.column_dimensions[col].width = w

    header_font = Font(bold=True)
    header_fill = PatternFill("solid", fgColor="DDEBF7")
    for cell in ws[1]:
        cell.font = header_font
        cell.fill = header_fill
        cell.alignment = Alignment(horizontal="center", vertical="center", wrap_text=True)

    wrap = Alignment(wrap_text=True, vertical="top")
    for row in ws.iter_rows(min_row=2, max_row=ws.max_row, min_col=1, max_col=len(COLUMNS)):
        for cell in row:
            cell.alignment = wrap

    ws.freeze_panes = "A2"
    ws.auto_filter.ref = ws.dimensions

print(f"OK: {len(df)} rows -> {OUT}")
